apiVersion: smithery.ai/v1
kind: MCPServer
metadata:
  name: msl-mcp-server
  version: "1.0.0"
  description: "MSL (Macro Scripting Language) MCP Server with AI Integration"
  author: "ImOrenge"
  license: "MIT"
  repository: "https://github.com/ImOrenge/MslMcpServer1.0.0"
  tags:
    - macro
    - scripting
    - gaming
    - automation
    - msl
    - ai-powered

spec:
  # Python 런타임 설정
  runtime: python
  pythonVersion: "3.11"
  
  # HTTP 서버 실행 명령
  command: ["py", "simple_http_server.py"]
  
  # 환경변수
  env:
    OPENAI_API_KEY:
      description: "OpenAI API key for AI-powered MSL generation"
      required: false
      secret: true
    MSL_DEBUG:
      description: "Enable debug mode"
      default: "false"

  # 포트 설정
  port: 8000
  
  # 헬스체크
  healthCheck:
    path: "/health"
    timeout: 5
    interval: 30

  # 리소스 제한
  resources:
    memory: "256Mi"
    cpu: "250m"

  # MCP 도구 목록
  tools:
    - name: "parse_msl"
      description: "Parse and analyze MSL scripts"
    - name: "generate_msl" 
      description: "Generate MSL scripts from natural language using AI"
    - name: "validate_msl"
      description: "Validate MSL script syntax and safety"
    - name: "optimize_msl"
      description: "Optimize MSL scripts for better performance"
    - name: "explain_msl"
      description: "Explain MSL scripts in educational detail"
    - name: "msl_examples"
      description: "Provide categorized MSL script examples"

  # API 엔드포인트
  endpoints:
    - path: "/health"
      method: "GET"
      description: "Health check endpoint"
    - path: "/parse"
      method: "POST"
      description: "Parse MSL scripts"
    - path: "/validate"
      method: "POST"
      description: "Validate MSL scripts"
    - path: "/examples"
      method: "GET"
      description: "Get MSL examples" 